[build]
  # No build command needed for static site
  command = ""
  
  # Publish the root directory
  publish = "."

[build.environment]
  # Node.js version (not needed but good to specify)
  NODE_VERSION = "18"

[[redirects]]
  # Redirect root to main app
  from = "/"
  to = "/advanced_converter.html"
  status = 200

[[redirects]]
  # Handle SPA routing
  from = "/*"
  to = "/advanced_converter.html"
  status = 200

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  # Cache static assets
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  # CORS headers for API access (if needed)
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"